# constants.py

"""This module defines project-level constants."""

CONFIG_FILE = "./config.json"
CH1 = 0
CH2 = 1

# SystemController CLASS
ERR_NO_ERROR = 0
ERR_INVALID_ARG = 1
ERR_NO_CALIBRATION = 2
ERR_DELAY_NOT_SET = 3
ERR_DELAY_OUT_OF_RANGE = 4
ERR_MOTOR_POS_DELTA_NOT_ZERO = 5


# used in Trombone and Motor
COM_PORT_5 = "/dev/ttyAMA0"
COM_PORT_3 = "/dev/ttyAMA1"

# CONSTANTS DEFINED FOR MOTOR
MOTOR_SC_CODE_ALARM_PRESENT = 0x0200
MOTOR_IS_INPUT_STATUS_OPTO_BIT_ON = 0x01
MOTOR_DI_STOP_DISTANCE_AFTER_SENSOR = 1
#MOTOR_MAX_NUMBER_MOTOR_STEPS = 525000

MOTOR_ACK_RESPONSE_IMM = "0%\r"
MOTOR_ACK_RESPONSE_BUF = "0*\r"

# CONSTANTS DEFINED FOR TROMBONE

#MOTOR_STEPS_PER_ONE_PS = 830.5
#MOTOR_STEPS_PER_FIVE_PS = 4152.50
MOTOR_STEPS_PER_ONE_PS = 833.3
MOTOR_STEPS_PER_FIVE_PS = 4167
#MOTOR_MAX_NUMBER_MOTOR_STEPS = 524475
#MOTOR_MAX_NUMBER_MOTOR_STEPS_TO_630 = 525000
MOTOR_MAX_NUMBER_MOTOR_STEPS_TO_632PT5 = 527083 

TROMBONE_NUM_CAL_TABLE_ENTRIES = 1251   # FROM 0 TO 1250 INDEX


