# constants.py

"""This module defines project-level constants."""

CONFIG_FILE = "./config.json"
CH1 = 0
CH2 = 1

# SystemController CLASS
ERR_NO_ERROR = -1
ERR_INVALID_ARG = 1
ERR_NO_CALIBRATION = 2
ERR_DELAY_NOT_SET = 3
ERR_DELAY_OUT_OF_RANGE = 4

# used in Trombone and Motor
COM_PORT_5 = "/dev/ttyAMA0"
COM_PORT_3 = "/dev/ttyAMA1"

# CONSTANTS DEFINED FOR MOTOR
SC_CODE_ALARM_PRESENT = 0x0200
IS_INPUT_STATUS_OPTO_BIT_ON = 0x01
DI_STOP_DISTANCE_AFTER_SENSOR = 1
MAX_NUMBER_MOTOR_STEPS = 525000

ACK_RESPONSE_IMM = "0%\r"
ACK_RESPONSE_BUF = "0*\r"

# CONSTANTS DEFINED FOR TROMBONE

MOTOR_STEPS_PER_ONE_PS = 830.5
MOTOR_STEPS_PER_FIVE_PS = 4152.50
MAX_NUMBER_MOTOR_STEPS = 524475

